### ISSUE TITLE
Review Microtasks

### ISSUE THREAD

**Issue by vchrombie** [rohanreddych/chaoss-microtasks#1]
Hi @rohanreddych, thanks for showing interest in applying for the GrimoireLab idea and working on the microtasks as a part of the GSoC program.

You can open an issue per microtask with the title `Review Microtask <num>`. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask. I can help with reviewing the microtasks and suggest some improvements.

Thanks!

**Comment by rohanreddych** [comment]
Hello @vchrombie should I open an issue in this repository itself?

**Comment by vchrombie** [comment]
> Hello @vchrombie should I open an issue in this repository itself?

Yes, you have to open the issues in this repository itself.

**Comment by vchrombie** [comment]
### Review Microtask 1

https://github.com/rohanreddych/chaoss-microtasks/blob/main/microtask1.md

It would be great if you can explain briefly about the steps you have followed, what problems you have faced and how you have fixed them. Also, add some screenshots if possible.

**Comment by vchrombie** [comment]
Thanks for working on the microtasks, please make sure you submit the proposal on the GSoC website as well as add your entry in the governance repository before the deadline.
