### ISSUE TITLE
Review Microtask2

### ISSUE THREAD

**Issue by rohanreddych** [rohanreddych/chaoss-microtasks#2]
https://github.com/rohanreddych/chaoss-microtasks/blob/main/microtask2.md

**Comment by vchrombie** [comment]
@rohanreddych, I just checked the [document](https://github.com/rohanreddych/chaoss-microtasks/blob/main/microtask2.md).

> I got an error, access denied for 'augur'@172.17.0.1 if anyone else faced the same problem you can look here.

Is this from the GrimoireLab project?
Do you remember how did you reproduce this?

**Comment by rohanreddych** [comment]
It was a mysql error. The link shows how to create a new user and change password

**Comment by vchrombie** [comment]
Oh okay, your MySQL username was `augur`. It makes sense now. Thanks for clarifying.

**Comment by vchrombie** [comment]
> I setup elasticsearch, kibiter, mariadb using docker-compose as mentioned in tutorial.

The tutorial is a bit outdated and it doesn't have the updated docker configurations. The tutorial has configurations for elasticsearch 6.1.0 and kibiter 6.1.4 but we have upgraded to elasticsearch 6.8.6 and kibiter 6.8.6 versions.

As mentioned in the GSoC issue, you can use the latest configurations.
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#getting-the-containers-

I know it doesn't affect the working much but it is advisable to use the latest images.

**Comment by rohanreddych** [comment]
Yes, I forgot to update the microtask file. I have updated it now.

**Comment by vchrombie** [comment]
> Yes, I forgot to update the microtask file. I have updated it now.

Perfect! Thanks.
LGTM.
