### ISSUE TITLE
Review microtask 7

### ISSUE THREAD

**Issue by rohanreddych** [rohanreddych/chaoss-microtasks#7]
https://github.com/rohanreddych/chaoss-microtasks/blob/main/microtask7.md

**Comment by vchrombie** [comment]
It would be great if you can add the python script to the repo instead of writing code in the markdown file.

**Comment by rohanreddych** [comment]
I actually cleared and exported a jupyter-notebook as markdown because the output was too big. I uploaded the original. https://github.com/rohanreddych/chaoss-microtasks/tree/main/microtask7 the notebook has some explanation as well

**Comment by vchrombie** [comment]
I see the notebook is too long. You don't need to parse the whole file, I understand there is a lot of content in that actual txt file. Take a small excerpt from the actual file and try using that.

**Comment by rohanreddych** [comment]
I update the notebook. Took 11 data items and we can see the graphql mutation query and the UUID returned after inserting that data into database.
https://github.com/rohanreddych/chaoss-microtasks/blob/main/microtask7/microtask7.ipynb

**Comment by vchrombie** [comment]
Thanks, I will check the task later this evening. It would be great if you can upload the txt file too.

**Comment by vchrombie** [comment]
The notebook looks good to me, it would be great if you can upload the txt file too. It would help us to run the notebook incase we want to.

Also, I checked your explanation and django code towards the bottom of the notebook. Do you think it is not possible to post the data without that code?

**Comment by rohanreddych** [comment]
>Also, I checked your explanation and django code towards the bottom of the notebook. Do you think it is not possible to post the data without that code?

I will once try to execute it from a script, instead of jupyter notebook and will inform you. (It gave 403 CSRF error with the same query)

**Comment by rohanreddych** [comment]
I tried to make a request after removing the code that i added. Still got the same error.
```
CSRF verification failed. Request aborted.</p>\n\n\n  <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>\n  <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for â\x80\x9csame-originâ\x80\x9d request
```

**Comment by vchrombie** [comment]
Hi @rohanreddych, I think you can fix this by commenting out this line https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/config/settings/devel.py#L24

This is not advisable for the project tho, but it should for that task. Can you try this and let me know if it worked?

**Comment by rohanreddych** [comment]
It works fine if we comment out that line. `Response [200]` :+1:

**Comment by vchrombie** [comment]
Thanks for confirming it.
